language: ruby
notifications:
  email: false
sudo: true
before_install:
  - tar zxvf shunit2-2.1.6.tgz
script: 
  - sudo apt-get install kcov
  - kcov coverage tests/test
  - bash <(curl -s https://codecov.io/bash)
